### ISSUE TITLE
Question: can I load and use trained tfdf model in Golang?

### ISSUE THREAD

**Issue by Arnold1** [tensorflow/decision-forests#115]
is there a way I can do model inference with golang?
what are the current options?

TF C API seems to miss a few inference ops. there is https://github.com/google/yggdrasil-decision-forests but might be hard to use it with golang?

**Comment by rstz** [comment]
Hi,
unfortunately,  TF-DF has no support for Golang at this time. We are considering it for future releases if there is sufficient interest (no timeline though)

**Comment by Arnold1** [comment]
@rstz how much would it to call c++ Yggdrasil-decision-forest code from golang?

**Comment by janpfeifer** [comment]
hi @Arnold1 , it should work with [cgo](https://pkg.go.dev/cmd/cgo), but likely you will want to write some wrappers around the C++ libraries that you want to use. Mind the usual ["cgo is not go" concerns](https://dave.cheney.net/2016/01/18/cgo-is-not-go) -- it looks dire, but in some cases the "cons" are ok.

I personally considered doing it on the side more than once, but then I gave up because of the complicated packaging of the mixed go/C++ libraries (I've never done it ...). But it would be awesome if someone would write a binding to TF-DF (Yggdrasil actually) to Go ;) ;)

From our side we have a draft **inference only** library written purely in Go -- it's not the most optimized version of the library, but in the majority of the cases DF are so fast that it doesn't matter (it's our internal use case here). 

We can't give an ETA, but I'll mark the issue as "enhancement" and leave this opened, so we can post an update when we have one.

**Comment by Arnold1** [comment]
@janpfeifer library purely in Go seems amazing - any plans for releasing over the summer? that would be amazing - I would have use case to use it in prod.

**Comment by janpfeifer** [comment]
hi @Arnold1 , we just released a [TF-DF (and YDF) inference API in Go](https://github.com/google/yggdrasil-decision-forests/tree/main/yggdrasil_decision_forests/port/go).

It's fresh from the oven, so we consider it beta. But internally it has already been used successfully.

Also it doesn't support all types of models yet, but should be easier now to add any model type. If you see the need just ping us.
