### ISSUE TITLE
[question] ERROR: Config value 'release_cpu_linux' is not defined in any .rc file

### ISSUE THREAD

**Issue by Genuifx** [tensorflow/decision-forests#143]
I'm using `armswdev/tensorflow-arm-neoverse` image and bazel-linux-arm64 to build this project.

After setup the docker container, I run `TF_VERSION=mac-arm64 ./tools/test_bazel.sh`, but `bazel` got the error 

`ERROR: Config value 'release_cpu_linux' is not defined in any .rc file`.

I'm new to bazel, and have no idea what's wrong happening here.

bazel version: bazel release 5.1.1
docker image: armswdev/tensorflow-arm-neoverse

**Comment by rstz** [comment]
Hi,

we're not actively supporting ARM64 builds outside MacOS, so this is mostly guesswork.

It looks like you're combining the build options for MacOS Arm64 with an Ubuntu docker. This will likely not work, since the MacOS build depends on the `tensorflow-macos` package. You will probably be more successful if you can find out which flags need to be set for building TF on this docker, maybe [these instructions](https://github.com/ARM-software/Tool-Solutions/blob/main/docker/tensorflow-aarch64/README.md#build-tensorflow-2x-for-aarch64-using-docker) can help. Then you can adjust the TF-DF's bazelrc file to make sure it passes the right parameters to the Tensorflow build.

**Comment by Genuifx** [comment]
Thanks for your response. I will make a try.
