### ISSUE TITLE
Installation and use are not supported on windwos.

### ISSUE THREAD

**Issue by TonyEinstein** [tensorflow/decision-forests#167]
Installation and use are not supported on windwos.

**Comment by TonyEinstein** [comment]
Hi, thanks a lot for creating this great package!. Is there an expected timeline for the Windows release? Thanks!

**Comment by rstz** [comment]
Hi, since Tensorflow does currently not support Tensorflow, we currently have no plans for a Windows release. However, our C++ library [Yggdrasil Decision Forests](https://github.com/google/yggdrasil-decision-forests) that TF-DF is based on can be built on Windows to train and serve TF-DF models.

**Comment by DLumi** [comment]
@rstz What do you mean by "Tensorflow does currently not support Windows"? 
You can install CPU version of the package just fine on Windows. Yeah, if you need GPU support (as you'd normally would for training), you'd have to install it on WSL machine, but if you need to inference some light model, or mess with tensor operations - it's perfectly fine to do that on Windows machine.
Hell, I don't even need TFDF, but TFJS converter that I use thinks otherwise, as it's listed as a dependency on versions above 3.18.

**Comment by rstz** [comment]
That's not a great situation, thank you for letting us know. Reopening this and investigating. If anyone manages to compile TF-DF on Windows, feel free to let me know

**Comment by highfive52** [comment]
I appreciate open source communities, but this is odd that tensorflow-decision-forests doesn't work on Windows when tensorflow seems to work just fine.  I found tensorflow_decision_forests while reading https://blog.tensorflow.org/2022/04/how-to-migrate-from-boostedtrees.html.
