### ISSUE TITLE
GPU support

### ISSUE THREAD

**Issue by Howard-ll** [tensorflow/decision-forests#37]
I just wanted to know if there is a plan for GPU.
My codes are in tensorflow. Therefore, running on GPU is very important in terms of throughput.

**Comment by janpfeifer** [comment]
There is no concrete plans yet: we do have some experimental implementation and it does help. But not by as much as you may expect, since decision forests is not so much about number crunching.

We would like to work on that, but it's lower on our priority list, so no ETA we can give.

Feel free to open an enhancement type of request, we like those to keep track, and help gauge the interest -- which in turn guides our prioritization.

**Comment by Howard-ll** [comment]
I see. If so, is there a plan for
